language: rust
sudo: required
dist: trusty

before_install:
  - cd diffusion_stereo

addons:
    apt:
        packages:
            - libssl-dev

cache: cargo

rust:
    - stable

branches:
    only:
        - master

before_cache:
    - cargo install cargo-tarpaulin -f

script:
    - cargo clean
    - cargo build
    - cargo test

after_success:
    - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
